NerdDinner/Controllers/DinnerController.cs
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using NerdDinner.Data;
using NerdDinner.Models;


namespace NerdDinner.Controllers
{
    [Authorize]
    public class DinnerController : Controller
    {
        private readonly NerdDinnerContext _context;
        private readonly INerdDinnerRepository _repository;

        private readonly UserManager<IdentityUser> _userManager;

        public DinnerController(NerdDinnerContext context, INerdDinnerRepository repository, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _repository = repository;
            _userManager = userManager;

        }

        [HttpGet("isUserHost")]
        [AllowAnonymous]
        public IActionResult IsUserHost(int id)
        {
            if (_userManager.GetUserId(User) == null)
            {
                return new ObjectResult(false);
            }

            var dinner = _repository.GetDinner(id);
            var user = _userManager.GetUserId(User);
            return new ObjectResult(dinner.IsUserHost(user));
        }

        [HttpGet("isUserRegistered")]
        [AllowAnonymous]
        public IActionResult IsUserRegistered(int id)
        {
          
            if (_userManager.GetUserId(User) == null)
            {
                return new ObjectResult(false);
            }

            var dinner = _repository.GetDinner(id);
            var UserName = _userManager.GetUserName(User);
            return new ObjectResult(dinner.IsUserRegistered(UserName));
        }



        // GET: Dinner
        [AllowAnonymous]
        public IActionResult Index()
        {
            return View(_repository.GetDinnersList());
        }

        // GET: Dinner/Details/5
        [AllowAnonymous]
        public IActionResult Details(long id)
        {
            var dinner = _repository.GetDinner(id);
            if (dinner == null)
            {
                return NotFound();
            }

            return View(dinner);
        }

        // GET: Dinner/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Dinner/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Dinner dinner)
        {
            var UserName = _userManager.GetUserName(User);
            dinner.UserName = UserName;
            if (ModelState.IsValid)
            {
                _repository.CreateDinner(dinner);
                return RedirectToAction(nameof(Index));
            }
            return View(dinner);
        }

        // GET: Dinner/Edit/5
        public IActionResult Edit(long id)
        {

            var dinner = _context.Dinners.Find(id);
            var user = _userManager.GetUserName(User);
            if (!dinner.IsUserHost(user))
            {
                return View("~/Views/Dinner/permission.cshtml");
            }

            if (dinner == null)
            {
                return NotFound();
            }
            return View(dinner);
        }

        // POST: Dinner/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(long id, Dinner dinner)
        {
            if (id != dinner.DinnerId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                dinner = _repository.UpdateDinner(dinner);
                return RedirectToAction(nameof(Index));
            }

            return View(dinner);
        }

        // GET: Dinner/Delete/5
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dinner = _context.Dinners
                .FirstOrDefault(m => m.DinnerId == id);
            var user = _userManager.GetUserName(User);
            if (!dinner.IsUserHost(user))
            {
                return View("~/Views/Dinner/permission.cshtml");
            }

            if (dinner == null)
            {
                return NotFound();
            }

            return View(dinner);
        }

        // POST: Dinner/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(long id)
        {
            _repository.DeleteDinner(id);
            return RedirectToAction(nameof(Index));
        }

        private bool DinnerExists(long id)
        {
            return _context.Dinners.Any(e => e.DinnerId == id);
        }

        

    }
}

NerdDinner/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NerdDinner</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.6.0/dist/leaflet.css"
          integrity="sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ=="
          crossorigin="" />
    <script src="https://unpkg.com/leaflet@1.6.0/dist/leaflet.js"
            integrity="sha512-gZwIG9x3wUXg2hdXF6+rVkLF/0Vi9U8D2Ntg4Ga5I5BZpVkVxlJWbSQtXPSiUTtC0TjtGOmxa1AJPuV0CPthew=="
            crossorigin=""></script>

</head>
<body>
    <header>
        
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <a class="navbar-brand badge-dark" asp-controller="Home" asp-action="Index">NerdDinner</a>
            <span class="navbar-toggler-icon"></span>
        </button>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <ul class="nav nav-tabs">
                    <li class="nav-item">
                        <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                            <ul class="navbar-nav flex-grow-1">
                                <li class="nav-item">
                                    <a class="nav-link active text-dark" asp-controller="Dinner" asp-action="Index">Dinners</a>
                                </li>
                            </ul>
                        </div>
                        <!--<a class="nav-link active" href="#">Active</a>-->
                </ul>
                <!--<li class="nav-item">
                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </li>-->
                <div>
                    <ul class="navbar-nav flex-grow-1">
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <form method="post" asp-action="logout" asp-controller="account">
                                    <button class="nav-link btn btn-link py-0" style="width:auto">
                                        Logout @User.Identity.Name
                                    </button>
                                </form>

                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="account" asp-action="register">
                                    Register
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="account" asp-action="login">
                                    Login
                                </a>
                            </li>
                        }

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - NerdDinner - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>